# Site Settings
locale                   : "en"
title                    : "Annals of Ommatidia"
title_separator          : ":"
name                     : "Gergely Nagy"
description              : "A trackball in the making"
#url                      : "https://algernon.github.io"
#baseurl                  : "/Ommatidia"
repository               : "algernon/Ommatidia"
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"

words_per_minute         : 200
breadcrumbs              : true

# Site Author
author:
  name             : "Gergely Nagy"
  avatar           : "https://trunk.mad-scientist.club/system/accounts/avatars/000/000/001/original/e54cf895c79a893c.jpg"
  bio              : "A tiny mouse, a hacker."
  uri              : "https://asylum.madhouse-project.org/"
  github           : "algernon"
  keybase          : "algernon"

# Reading Files
include:
  - _pages
  - assets
exclude:
  - .sass-cache
  - Gemfile
  - COPYING
  - README.md
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /posts/:year-:month-:day-:title/
paginate: 1000
timezone: "Europe/Budapest"

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-remote-theme

compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      excerpt: ""

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
